### PR TITLE
[BACK-2984] Resolve dependabot issues

### PR DESCRIPTION
**Pull request by darinkrauss**
- Fix dependencies issues and vulnerabilities
- Use modern version of yarn
- Update Dockerfile
- Update .travis.yml
- Update .gitgnore and .dockerignore
- Update .nvmrc
- Add .yarnrc.yml
- Add .snyk
- Use Node v20.8.0
- https://tidepool.atlassian.net/browse/BACK-2984

### CODE REVIEW

**Review by jh-bate — APPROVED** [review]
LGTM

 - note that this has version `"version": "1.7.3-alpha.1"` so just wanted to check that was intentional

**Comment by darinkrauss** [comment]
Thanks, yes, that's intentional. Once it is tested I'll move it to 1.7.3, release a new version, and pick up that change in the export repo.

**Review by jh-bate — APPROVED** [review]
Lgmt

**Pull request merged**
